# Generated by Django 3.1.6 on 2021-07-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210722_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_price',
            field=models.IntegerField(null=True),
        ),
    ]
