# Generated by Django 3.1.6 on 2021-07-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210722_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
