# Generated by Django 3.1.6 on 2021-07-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210722_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='BottomThickness',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='TopHeight',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='TopThickness',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='TotalWeight',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='styleno',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
