# Generated by Django 3.1.6 on 2021-07-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210723_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BottomThickness',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='TopHeight',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='TopThickness',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='TotalWeight',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
