# Generated by Django 3.1.6 on 2021-07-23 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210723_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=20)),
                ('subtotal', models.IntegerField(max_length=15)),
                ('Prodect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
