# Generated by Django 3.1.6 on 2021-07-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_detail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderstatus', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packing', 'Packing'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.detail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
